### ISSUE TITLE
DOI for referencing this work.

### ISSUE THREAD

**Issue by jbusecke** [xgcm/fastjmd95#10]
I am writing up a manuscript and will likely cite this package (unless the stupid citation limit comes into play). Does this already have a DOI?

**Comment by rabernat** [comment]
No. It would be great if you could set up zenodo.

**Comment by jbusecke** [comment]
Ok I set it up, but we need to release a version. Anything speaking against bumping the fix number one up just for this purpose?

**Comment by rabernat** [comment]
Fine with me! We have a release workflow already: https://github.com/xgcm/fastjmd95/blob/master/.github/workflows/python-publish.yml

Just create a release in github.

**Comment by jbusecke** [comment]
Done. I also created a PR to add a DOI badge in #11. Ill close this now.
